version: "3.0"
services:
    frontend:
        build: ./frontend
        volumes:
            - ./frontend/src:/app
            - /app/node_modules
        ports:
            - 80:80
        environment:
            - CHOKIDAR_USEPOLLING=true
        tty: true
        restart: always

    backend:
        build: ./backend
        volumes:
            - ./backend/src:/go/src/server
        ports:
            - 3000:3000
        command: realize start --name='server' --run
        tty: true
        restart: always
        